services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: drgnj
      MYSQL_USER: azer
      MYSQL_PASSWORD: "12345"
      MYSQL_DATABASE: graduation
  adminer:
    image: adminer
    ports:
      - "8080:8080"
